POST http://localhost:5005/api/transactions/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJtYXJjb3NvbGRhIiwiaWF0IjoxNjQ3MTI0MTgyfQ.pkBEUaPzaZWHG92jmXD9fiWNxBAf4yTOT8QVWfGfo50

{
  "concept": "endpoint con token",
  "amount": "25500",
  "date": "12/03/22",
  "id_type_transaction": "1",
  "category_id": "0"
}