POST http://localhost:5005/api/transactions/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJtYXJjb3NvbGRhIiwiaWF0IjoxNjQ1NTM0MDE5fQ.j9Lw7NWTsxRLlSii0wdKnr5_61NOizeHQn1TfTu_840

{
  "concept": "compraDeMateriales2",
  "amount": "35000",
  "date": "22/02/22",
  "id_type_transaction": "2",
  "category_id": "0"
}